export const STATUS_META = {
  Open: { label: 'Open', modifier: 'open' },
  Escalated: { label: 'Escalated', modifier: 'escalated' },
  Resolved: { label: 'Resolved', modifier: 'resolved' },
};

export const INITIAL_COMPLAINTS = [
  {
    id: 'CMP-1007',
    description: 'Projector not working in Lab B — cables loose, image distorted',
    raisedBy: 'Aditya Sharma',
    date: '19 Aug 2026',
    status: 'Open',
    location: 'Lab B',
    level: 'Lab Incharge',
    history: ['19 Aug 2026 — Complaint raised by Aditya Sharma'],
  },
  {
    id: 'CMP-1006',
    description: 'PC #14 fails to boot — shows BSOD on startup',
    raisedBy: 'Priya Menon',
    date: '18 Aug 2026',
    status: 'Escalated',
    location: 'Lab A, PC #14',
    level: 'HOD',
    history: [
      '18 Aug 2026 — Complaint raised by Priya Menon',
      '18 Aug 2026 — Escalated to HOD by Lab Incharge',
    ],
  },
  {
    id: 'CMP-1005',
    description: 'Internet not accessible on workstations in Row C',
    raisedBy: 'Rohan Verma',
    date: '17 Aug 2026',
    status: 'Resolved',
    location: 'Lab C, Row C',
    level: 'Lab Incharge',
    history: [
      '17 Aug 2026 — Complaint raised by Rohan Verma',
      '17 Aug 2026 — Resolved by Lab Incharge',
    ],
  },
  {
    id: 'CMP-1004',
    description: 'UPS unit beeping continuously near server rack',
    raisedBy: 'Sneha Iyer',
    date: '17 Aug 2026',
    status: 'Open',
    location: 'Server Room',
    level: 'Lab Incharge',
    history: ['17 Aug 2026 — Complaint raised by Sneha Iyer'],
  },
  {
    id: 'CMP-1003',
    description: 'Keyboard and mouse unresponsive on station #7',
    raisedBy: 'Arjun Nair',
    date: '16 Aug 2026',
    status: 'Resolved',
    location: 'Lab A, Station #7',
    level: 'Lab Incharge',
    history: [
      '16 Aug 2026 — Complaint raised by Arjun Nair',
      '16 Aug 2026 — Resolved by Lab Incharge',
    ],
  },
  {
    id: 'CMP-1002',
    description: 'AC unit in Lab A not cooling — temperature rising',
    raisedBy: 'Deepa Krishnan',
    date: '15 Aug 2026',
    status: 'Escalated',
    location: 'Lab A',
    level: 'HOD',
    history: [
      '15 Aug 2026 — Complaint raised by Deepa Krishnan',
      '15 Aug 2026 — Escalated to HOD by Lab Incharge',
    ],
  },
  {
    id: 'CMP-1001',
    description: 'Software license expired on CAD workstations',
    raisedBy: 'Vikram Rao',
    date: '14 Aug 2026',
    status: 'Open',
    location: 'Lab B, CAD Workstations',
    level: 'Lab Incharge',
    history: ['14 Aug 2026 — Complaint raised by Vikram Rao'],
  },
];
